In [1]:
# 对于np.hstack函数的理解
# transition = np.hstack((s, [a, r], s_))
import numpy as np

arr1 = [1,2,3]
arr2 = [4,5]
arr3 = [6,7]
res = np.hstack((arr1, arr2,arr3))
print (res)

[1 2 3 4 5 6 7]


In [5]:
# % 实现循环，实现新的experience取代老的experience
# index = self.memory_counter % self.memory_size
a = 500 % 500
b = 501 % 500
c = 502 % 500

print(a , b, c)

0 1 2


In [6]:
# np.newaxis示例
# np.newaxis的意思是给数组新增一个维度。“python中矩阵切片维数微秒变化”中介绍了矩阵切片有时候会降低矩阵维度，为保证维度不变，可以用np.newaxis新增一个维度。
import numpy as np

a=np.array([1,2,3])

b=a[np.newaxis,:]
c=a[:,np.newaxis]

print("b=\n",b)
print("c=\n",c)

b=
 [[1 2 3]]
c=
 [[1]
 [2]
 [3]]


# np.random.randint()解释
numpy.random.randint(low. high=None, size=None, dtype='l')
函数的作用是，返回一个随机整型数，其范围为[low, high)。如果没有写参数high的值，则返回[0,low)的值。
从random可以看出是产生随机数，randint可以看出是产生随机整数（int）
参数作用如下：
参数如下：
low: int
表示生成的数值大于等于low。
（hign = None时，生成的数值要在[0, low)区间内）
high: int (可选)
如果使用这个值，则生成的数值在[low, high)区间
size: int or tuple of ints(可选)
输出随机数组的尺寸，比如size = (m, n, k)，则输出数组的shape = (m, n, k)，数组中的每个元素均满足要求。size默认为None，仅仅返回满足要求的单一随机数。
dtype: dtype(可选)：
想要输出的格式。如int64、int等等
输出：

out: int or ndarray of ints
返回一个随机数或随机数数组



In [17]:
a = np.random.randint(2,10,size=(2,3))
# 在2-10之间生成随机整数，组成一个两行三列的数组
print(a)

[[7 6 4]
 [3 6 3]]
[7 6 4]


理解torch.max(a,1)的用法

In [2]:
# torch.max(a,1)返回每一行中最大值的那个元素，且返回其索引（返回最大元素在这一行的列索引）
import torch

a = torch.randn(3,3)
print('a', a)
torch.max(a,1)

a tensor([[-0.4623, -1.0143,  0.8979],
        [-0.1879, -2.3150,  0.1675],
        [ 1.2072,  0.1098,  0.2588]])


torch.return_types.max(
values=tensor([0.8979, 0.1675, 1.2072]),
indices=tensor([2, 2, 0]))